// AUTO-GENERATED by scripts/fetch-project-durations.mjs — do not edit
import type { ProjectDuration } from "@/data/projects";

export const projectDurations: Record<string, ProjectDuration> = {
  "mindscope": {
    "startDate": "2026-04-10T10:43:25Z",
    "endDate": "2026-04-11T02:11:59Z",
    "totalDays": 1
  }
};
